# This is a basic workflow to help you get started with Actions

name: MY_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-test
        run: |
          cd main
          go build 
          cd ../cal
          go build
          echo build-test end...
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit-test
        run: |
          cd cal
          go test
          echo unit-test end...
  run-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-main
        run: |
          cd main
          go build -o main
          ./main
          echo run-main end...
  
